<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Stripe\Stripe;
use Stripe\Exception\CardException;

class PaymentController extends Controller
{
    public function handlePayment(Request $request)
    {
        // Set your Stripe API key
        Stripe::setApiKey(config('services.stripe.secret'));

        try {
            // Create a charge
            $charge = \Stripe\Charge::create([
                'amount' => $request->amount * 100, // Stripe requires amount in cents
                'currency' => 'eur',
                'source' => $request->stripeToken, // Token generated by Stripe.js
                'description' => 'Payment for Product', // Description for the charge
            ]);

            // Payment successful, do something (e.g., update database, send confirmation email)

            return redirect()->route('checkout.success')->with('success_message', 'Payment successful.');
        } catch (CardException $e) {
            // If the card is declined, display error message to the user
            return back()->withErrors(['error' => $e->getMessage()]);
        } catch (\Exception $e) {
            // Other Stripe-related errors
            return back()->withErrors(['error' => $e->getMessage()]);
        }
    }
}
